--1
SELECT * FROM STUDENT
WHERE DIVISION='BCX-3'

--2
SELECT NAME FROM STUDENT
WHERE SEM=3
OR SEM=5

--3
SELECT * FROM STUDENT
WHERE NAME NOT LIKE 'V%'

--4
SELECT TOP 3 * FROM STUDENT

--5
SELECT DISTINCT DIVISION FROM STUDENT

--6
SELECT TOP 30 PERCENT NAME,ENROLLMENTNO FROM STUDENT 
WHERE CONTACTNO LIKE '%7'

--7
SELECT * FROM STUDENT
WHERE EMAIL LIKE '%3@g%'
AND DIVISION = 'BCZ-5'

--8
SELECT STUID,NAME,EMAIL FROM STUDENT

--9
SELECT * FROM STUDENT
WHERE BIRTHDATE>'1990-01-01'

--10
SELECT NAME FROM STUDENT
WHERE SEM=3
AND ENROLLMENTNO LIKE'%107%'

--11
SELECT NAME,DIVISION FROM STUDENT
ORDER BY NAME,DIVISION ASC

--12
SELECT * FROM STUDENT
WHERE CONTACTNO LIKE 'NULL'

--13
SELECT DISTINCT SEM AS SEMESTER FROM STUDENT

--14
SELECT NAME,ENROLLMENTNO,SEM FROM STUDENT
WHERE DIVISION IN ('BCX-3','BCZ-5','BCY-3')
AND BIRTHDATE>'1996-12-03'

--15
SELECT * FROM STUDENT
ORDER BY BIRTHDATE DESC